import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import SkillsList from '../components/SkillsList'
import ProjectsList from '../components/ProjectsList'
import Contact from '../components/Contact'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar-thin scrollbar-track-gray-400/40 scrollbar-thumb-[#f5a73a]/80'>
      <Head>
        <title>Nathan's Portfolio</title>
        {/* <meta name="description" content="Generated by create next app" />     // Sonny deletes this stuff
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
  
      <Header />

      <section id='hero' className='snap-start'>
        <Hero />
      </section>
      <section id='about' className='snap-center'>
        <About />
      </section>
      <section id='experience' className='snap-center'>
        <WorkExperience />
      </section>
      <section id='skills' className='snap-start'>
        <SkillsList />
      </section>
      <section id='projects' className='snap-start'>
        <ProjectsList />
      </section>
      <section id='contact' className='snap-start'>
        <Contact />
      </section>

      <Link href='#hero' legacyBehavior>
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex item-center justify-center '>
            <p className='h-10 w-40 text-center border border-[#f5a73a] rounded-full filter grayscale hover:grayscale-0'>Back to Top</p>
          </div>
        </footer>
      </Link>
    </div>
  )
}
